apiVersion: v1
kind: Service
metadata:
  name: chicstore-service
  namespace: chicstore
spec:
  selector:
    app: chicstore
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30080
