name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/chic-store-frontend:latest

      - name: Build and push Server image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/chic-server:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy Server to Minikube
        run: |
          kubectl apply -f k8s/server-deployment.yaml
          kubectl apply -f k8s/server-service.yaml

      - name: Deploy Frontend to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
